on:
  workflow_call:
    inputs:
      requirements-path:
        required: true
        type: string
        
jobs:
  cache-python:
    runs-on: ubuntu-latest
    steps:
    - name: Calculate Hash
    - name: Cache python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: $ {{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')
